# Generated by Django 3.1.4 on 2023-03-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            ["""
            INSERT INTO profiles_profile (
                user_id,
                favorite_city
            )
            SELECT 
                user_id,
                favorite_city
            FROM oc_lettings_site_profile;
            """]
        )
    ]
