# Generated by Django 3.0 on 2023-03-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            ["""
            INSERT INTO lettings_address (
                number,
                street,
                city,
                state,
                zip_code,
                country_iso_code
            )
            SELECT 
                number,
                street,
                city,
                state,
                zip_code,
                country_iso_code
            FROM oc_lettings_site_address;
            """]
        ),
        migrations.RunSQL(
            ["""
            INSERT INTO lettings_letting (
                title,
                address_id
            )
            SELECT
                title,
                address_id
            FROM oc_lettings_site_letting;
            """]
        )
    ]
