# Generated by Django 3.1.4 on 2023-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230331_1138'),
        ('profiles', '0002_auto_20230331_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
