name: GitHub Actions OC Letting Site
run-name: ${{ github.actor }} is running out GitHub Actions OC Letting Site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    matrix:
      python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          pytest