name: GitHub Actions OC Letting Site
run-name: ${{ github.actor }} is running out GitHub Actions OC Letting Site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          pytest
        env: 
          PORT: 80
          DEBUG: False
          ALLOWED_HOSTS: 'localhost'
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      - name: Log into the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build docker image
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site:${{github.sha}}
      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site:${{github.sha}}
      - name: Deploy to ec2
        run: |
          echo "${{ secrets.AWS_PRIVATEKEY }}" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOSTNAME }} '

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site:${{github.sha}}
            sudo systemctl restart docker
            docker run -d -p 80:80 -e "PORT=80" -e "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" -e "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" -e "ALLOWED_HOSTS='localhost 127.0.0.1 leacourdes-oc-lettings-site.link ${{ secrets.AWS_HOSTNAME }} ${{ secrets.AWS_IP_PUBLIC }}'" ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site:${{github.sha}}
          '
