name: GitHub Actions OC Letting Site
run-name: ${{ github.actor }} is running out GitHub Actions OC Letting Site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          pytest
      - name: Log into the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build docker image
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site/${{github.sha}}
      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings-site/${{github.sha}}
